export interface Post {
    id: number;
    category: string;
    title: string;
    content: string;
    author: string;
    time: string;
    likes: number;
    comments: number;
    views?: number;
    isHot?: boolean;
}

export const CATEGORIES = [
    { id: 'all', name: '전체' },
    { id: 'talk', name: '웨이터 소통방' },
    { id: 'region', name: '지역방' },
    { id: 'ssul', name: '웨이터 썰' },
    { id: 'tip', name: '웨이터 팁' },
    { id: 'market', name: '중고거래' },
    { id: 'legal', name: '무료법률상담' },
    { id: 'lounge', name: '프리미엄 라운지' },
] as const;

export type CategoryId = typeof CATEGORIES[number]['id'];

const RAW_MOCK_POSTS: Post[] = [
    // ── 프리미엄 라운지 ──────────────────────────────────────────
    {
        id: 40,
        category: '프리미엄 라운지',
        title: '형님들 진상 손님 블랙리스트 공유합니다 (필독)',
        content: '요즘 이상한 손님들이 너무 많네요. 직접 겪은 케이스 정리해서 공유합니다. 다들 조심하세요! 특히 2차 요구하거나 개인 연락처 요구하는 손님은 바로 매니저 부르세요.',
        author: '정보통형님',
        time: '5분 전',
        likes: 48,
        comments: 6,
        isHot: true,
    },
    {
        id: 42,
        category: '프리미엄 라운지',
        title: '웨이터 시작 3일차 수입 공개합니다',
        content: '걱정 많이 했는데 생각보다 잘 벌리네요. 고민하는 형님들 위해 용기 내서 올립니다! 첫날엔 좀 헤맸는데 둘째날부터 요령이 생기니까 수입이 확 늘었어요. 업소 분위기 파악이 제일 중요한 것 같습니다.',
        author: '뉴비형님',
        time: '20분 전',
        likes: 52,
        comments: 8,
        isHot: true,
    },
    {
        id: 82,
        category: '프리미엄 라운지',
        title: '20대에 1억 모으기 달성 인증 — 웨이터 3년 후기',
        content: '잠 안 자고 투잡 뛰고 재테크 공부해서 드디어 앞자리 바꿨어요! 처음엔 막막했는데 지출 관리 + 적금 + 소액 투자 병행하니까 눈에 보이더라고요. 비결 궁금한 형님들 댓글 달아주세요.',
        author: '자산가형님',
        time: '3시간 전',
        likes: 55,
        comments: 19,
        isHot: true,
    },
    {
        id: 88,
        category: '프리미엄 라운지',
        title: '매출 잘 나오는 업소 고르는 기준 공유 (경력 4년)',
        content: '업소 선택이 수입을 결정한다고 해도 과언이 아니에요. 위치, 주차, 고객층, 매니저 스타일까지 4년 동안 발로 뛰며 정리한 체크리스트 공유합니다. 댓글로 질문 주시면 답변할게요.',
        author: '4년차형님',
        time: '15시간 전',
        likes: 60,
        comments: 18,
        isHot: true,
    },
    {
        id: 17,
        category: '프리미엄 라운지',
        title: '멘탈 관리하는 루틴 공유 — 야근 많아도 버티는 법',
        content: '새벽까지 일하다 보면 멘탈이 먼저 나가더라고요. 저는 퇴근 후 30분 산책 + 주 3회 헬스로 버티고 있어요. 형님들만의 멘탈 관리법 있으면 공유해주세요!',
        author: '건강형님',
        time: '1시간 전',
        likes: 29,
        comments: 5,
    },
    {
        id: 35,
        category: '프리미엄 라운지',
        title: '업소 이직할 때 주의할 점 — 계약서 필수 확인 항목',
        content: '이직 3번 해보니까 계약서에서 꼭 봐야 할 항목들이 있더라고요. 수수료율, 주거 지원, 의류비 지원, 퇴직금 조항까지. 꼼꼼하게 챙기세요. 구두 약속은 절대 믿으면 안 됩니다.',
        author: '이직전문가',
        time: '2시간 전',
        likes: 24,
        comments: 7,
        isHot: true,
    },

    // ── 웨이터 소통방 ────────────────────────────────────────────
    {
        id: 1,
        category: '웨이터 소통방',
        title: '오늘 퇴근길 새벽 하늘 진짜 힐링이네요',
        content: '새벽 6시에 퇴근하는데 하늘이 너무 예쁘더라고요. 일하면서 힘든 것도 이런 순간에 충전되는 것 같아요. 형님들도 오늘 고생 많으셨어요!',
        author: '익명웨이터',
        time: '10분 전',
        likes: 12,
        comments: 2,
    },
    {
        id: 100,
        category: '웨이터 소통방',
        title: '이번 달 처음으로 세후 500 넘겼어요',
        content: '드디어 목표 달성했습니다. 6개월 만에 해냈네요. 처음엔 300도 힘들었는데 손님 응대 스타일 바꾸고 나서 수입이 달라졌어요. 다들 파이팅입니다!',
        author: '목표달성형님',
        time: '30분 전',
        likes: 43,
        comments: 16,
        isHot: true,
    },
    {
        id: 101,
        category: '웨이터 소통방',
        title: '웨이터 시작 고민 중인데 현실적으로 어떤가요?',
        content: '일반 알바 하다가 수입 때문에 고민 중이에요. 주위에서 걱정하는 시선도 있고... 형님들 처음 시작할 때 어떠셨어요? 솔직한 후기 부탁드립니다.',
        author: '고민중',
        time: '1시간 전',
        likes: 18,
        comments: 14,
    },
    {
        id: 102,
        category: '웨이터 소통방',
        title: '같이 일할 파트너 구합니다 (강남/홍대 권역)',
        content: '혼자 다니다 보니까 불편한 점이 많더라고요. 같이 정보 공유하고 위급 상황에 도움 주고받을 파트너 구합니다. 비슷한 경력이면 좋겠어요.',
        author: '파트너구함',
        time: '2시간 전',
        likes: 9,
        comments: 3,
    },

    // ── 웨이터 썰 ────────────────────────────────────────────────
    {
        id: 50,
        category: '웨이터 썰',
        title: '오늘 VIP 테이블에서 생긴 황당한 일 ㅋㅋ',
        content: '테이블 세팅하다가 손님이 갑자기 영어로만 대화하자고 해서 진땀뺐네요 ㅋㅋ 다행히 고등학교 때 영어 좀 했던 게 도움이 됐습니다. 손님도 결국 웃으면서 팁 두둑하게 주고 가셨어요.',
        author: '영어웨이터',
        time: '25분 전',
        likes: 57,
        comments: 15,
        isHot: true,
    },
    {
        id: 51,
        category: '웨이터 썰',
        title: '진상 손님 응대하다 진짜 웃긴 일 생겼어요 ㅋㅋ',
        content: '술값 계산하면서 "카드가 안 된다"고 우기는 손님이 있었는데 알고 보니 카드를 거꾸로 꽂으셨더라고요 ㅋㅋ 저도 참기 힘들었는데 표정 관리하고 도와드렸습니다.',
        author: '표정관리형님',
        time: '40분 전',
        likes: 44,
        comments: 12,
        isHot: true,
    },
    {
        id: 52,
        category: '웨이터 썰',
        title: '어제 일하다 연예인 마주쳤습니다 (실화)',
        content: '확실히 누군지는 말 못 하지만 꽤 유명한 분이셨어요. 직업 특성상 비밀 유지가 기본이라 아무 내색 안 했는데 퇴장하면서 명함 한 장 주고 가셨네요. 이런 만남도 있구나 싶었습니다.',
        author: '비밀유지형님',
        time: '1시간 전',
        likes: 59,
        comments: 22,
        isHot: true,
    },
    {
        id: 80,
        category: '웨이터 썰',
        title: '첫 출근날 실수 모음 — 3년 지나서야 웃으며 회상',
        content: '첫날 주문 받으러 갔다가 메뉴판을 거꾸로 들고 있었어요 ㅋㅋ 매니저님이 눈치채고 슬쩍 잡아주셨는데... 지금 생각하면 웃기지만 그때는 식은땀 흘렸네요. 신입 시절 썰 있으면 공유해주세요!',
        author: '3년차',
        time: '1시간 전',
        likes: 58,
        comments: 21,
        isHot: true,
    },
    {
        id: 81,
        category: '웨이터 썰',
        title: '손님이 갑자기 우는 거 어떻게 대처하세요?',
        content: '술자리 도중에 갑자기 감정이 북받쳐서 우시는 손님이 계셨어요. 위로해 드려야 할지 자리 피해야 할지 판단이 안 되더라고요. 형님들은 이런 상황 어떻게 대처하세요?',
        author: '대처법궁금',
        time: '2시간 전',
        likes: 36,
        comments: 14,
        isHot: true,
    },
    {
        id: 6,
        category: '웨이터 썰',
        title: '형님들 담배 끊는 법 좀 공유해주세요',
        content: '업소 특성상 간접흡연도 많고 스트레스받으면 더 피게 되더라고요. 건강 생각해서 끊어보려는데 쉽지 않네요. 성공한 형님들 방법 공유 부탁드립니다.',
        author: '금연도전',
        time: '4시간 전',
        likes: 9,
        comments: 3,
    },

    // ── 웨이터 팁 ────────────────────────────────────────────────
    {
        id: 41,
        category: '웨이터 팁',
        title: '수입 올리는 팁 — 단골 손님 관리가 핵심이에요',
        content: '신규 손님 유치도 중요하지만 단골 관리가 장기 수입의 핵심이에요. 손님 취향, 기념일, 선호 주류 등 메모해두면 재방문율이 확 달라집니다. 저는 이 방법으로 3개월 만에 수입 30% 올렸어요.',
        author: '단골관리형님',
        time: '12분 전',
        likes: 38,
        comments: 4,
        isHot: true,
    },
    {
        id: 18,
        category: '웨이터 팁',
        title: '피로 회복에 진짜 도움되는 영양제 추천 (내돈내산)',
        content: '야간 근무 특성상 피로가 누적되는데 이거 먹고 나서부터 아침이 달라졌어요. 홍삼 + 비타민B군 + 마그네슘 조합이 제일 효과적이었습니다. 내돈내산 찐후기예요.',
        author: '건강챙기기',
        time: '45분 전',
        likes: 15,
        comments: 4,
    },
    {
        id: 90,
        category: '웨이터 팁',
        title: '처음 업소 면접 볼 때 꼭 확인해야 할 것들',
        content: '면접 때 분위기에 흘러가다 보면 중요한 조건을 못 확인하고 계약하는 경우가 많아요. 수수료율, 정산 주기, 의류비 지원 여부, 고정 테이블 배정 방식 — 이 4가지는 반드시 확인하세요.',
        author: '면접전문가',
        time: '30분 전',
        likes: 43,
        comments: 16,
        isHot: true,
    },
    {
        id: 91,
        category: '웨이터 팁',
        title: '손님이 술 권할 때 음주 조절하는 현실적인 방법',
        content: '일하면서 음주량 조절 못 하면 건강도 망가지고 다음 날 업무도 힘들어요. 제가 쓰는 방법: 물 전략적으로 활용하기, 술잔 교체 타이밍 잡기, 단골 손님과 신뢰 쌓아서 양해 구하기. 효과 있었어요.',
        author: '절주형님',
        time: '1시간 전',
        likes: 37,
        comments: 12,
        isHot: true,
    },
    {
        id: 93,
        category: '웨이터 팁',
        title: '체형 관리 — 웨이터 현직들이 실제로 하는 운동 루틴',
        content: '외모 관리도 경쟁력이라 처음엔 어떻게 해야 할지 몰랐어요. 야간 근무 후 낮에 헬스 1시간 + 단백질 식단이 기본이 됐어요. 형님들만의 루틴 공유해주세요!',
        author: '헬스형님',
        time: '2시간 전',
        likes: 56,
        comments: 31,
        isHot: true,
    },
    {
        id: 33,
        category: '웨이터 팁',
        title: '대화 스킬 키우는 방법 — 어떻게 공부하세요?',
        content: '손님과 자연스러운 대화가 수입과 직결되더라고요. 저는 뉴스 매일 읽기 + 다양한 취미 갖기로 대화 소재를 넓혔어요. 형님들은 어떻게 대화 스킬 키우세요?',
        author: '토크고수',
        time: '30분 전',
        likes: 15,
        comments: 5,
    },

    // ── 지역방 ──────────────────────────────────────────────────
    {
        id: 83,
        category: '지역방',
        title: '강남 구역 업소 분위기 요즘 어때요?',
        content: '강남 쪽으로 이직 고민 중인데 요즘 분위기 어떤지 현직 형님들 의견 궁금합니다. 손님층이나 매출 흐름이 어떤지 공유해주시면 감사하겠습니다.',
        author: '이직고민',
        time: '4시간 전',
        likes: 27,
        comments: 11,
    },
    {
        id: 84,
        category: '지역방',
        title: '홍대/마포 쪽 신규 오픈 업소 정보 아시는 분?',
        content: '홍대 쪽에 새로 오픈한 업소 있다고 들었는데 구체적인 정보를 못 찾겠어요. 알고 계신 분 있으면 DM이나 댓글로 알려주세요.',
        author: '홍대형님',
        time: '5시간 전',
        likes: 53,
        comments: 24,
        isHot: true,
    },
    {
        id: 85,
        category: '지역방',
        title: '부산 서면 업소들 비교해봤어요 (3군데 면접 후기)',
        content: '서면 주요 업소 3군데 직접 면접 보고 비교해봤습니다. 수수료, 시설, 주차, 매니저 스타일까지 솔직하게 정리했어요. 부산 형님들께 도움이 됐으면 합니다.',
        author: '부산형님',
        time: '6시간 전',
        likes: 46,
        comments: 28,
        isHot: true,
    },
    {
        id: 86,
        category: '지역방',
        title: '인천 쪽 요즘 손님 줄었나요? 아니면 제 업소만?',
        content: '이번 달 들어서 손님이 갑자기 줄었는데 인천 전반적인 분위기인지 제 업소만 그런 건지 궁금해서요. 인천 형님들 공유 부탁드립니다.',
        author: '인천형님',
        time: '8시간 전',
        likes: 22,
        comments: 17,
    },
    {
        id: 87,
        category: '지역방',
        title: '수원/경기 남부 형님들 — 정기 모임 어떠세요?',
        content: '같은 지역 형님들끼리 정보 공유하는 소모임 만들고 싶어요. 부담 없이 한 달에 한 번 식사하면서 업계 정보 나누는 자리요. 관심 있는 분 댓글 달아주세요.',
        author: '모임추진형님',
        time: '12시간 전',
        likes: 49,
        comments: 20,
        isHot: true,
    },

    // ── 중고거래 ─────────────────────────────────────────────────
    {
        id: 92,
        category: '중고거래',
        title: '정장 수트 팝니다 — 105 사이즈, 3회 착용',
        content: '업소 면접용으로 샀는데 체형이 바뀌어서 팔아요. 브랜드: 갤럭시, 105 사이즈. 수선 없이 바로 입을 수 있어요. 원가 38만원, 15만원에 팝니다. DM 주세요.',
        author: '정장판매',
        time: '3시간 전',
        likes: 5,
        comments: 8,
    },
    {
        id: 94,
        category: '중고거래',
        title: '구두 구합니다 — 265 사이즈 블랙 정장화',
        content: '급하게 필요한데 265 블랙 정장구두 구합니다. 굽 있는 거 선호하지만 없어도 상관없어요. 상태 좋으면 가격은 협의 가능합니다.',
        author: '구두구함',
        time: '5시간 전',
        likes: 2,
        comments: 5,
    },
];

const RAW_MOCK_COMMENTS = [
    // postId: 40 (블랙리스트)
    { id: 4001, postId: 40, author: '정보감사', content: '이런 정보 너무 필요했어요! 저장해뒀어요', time: '3분 전' },
    { id: 4002, postId: 40, author: '조심해야지', content: '저도 비슷한 손님 만난 적 있는데 소름이네요', time: '7분 전' },
    { id: 4003, postId: 40, author: '공유고마워', content: '댓글로 추가 제보 주실 분 있나요?', time: '12분 전' },
    { id: 4004, postId: 40, author: '나도신고해', content: '저도 비슷한 케이스 있는데 공유해도 될까요?', time: '20분 전' },
    { id: 4005, postId: 40, author: '진짜무서워', content: '캡처해서 주변 형님들한테 공유했어요', time: '28분 전' },
    { id: 4006, postId: 40, author: '고마워요', content: '이런 글 올려주셔서 진짜 감사해요', time: '35분 전' },
    // postId: 42 (3일차 수입)
    { id: 4201, postId: 42, author: '궁금한형님', content: '대박이네요! 어떻게 준비하셨어요?', time: '5분 전' },
    { id: 4202, postId: 42, author: '나도해볼까', content: '저도 고민 중인데 무섭긴 해요 솔직히', time: '12분 전' },
    { id: 4203, postId: 42, author: '응원해요', content: '멋지다!! 저도 용기 내볼게요', time: '20분 전' },
    { id: 4204, postId: 42, author: '리얼후기감사', content: '첫날 어떻게 하셨는지 더 알려주세요!', time: '28분 전' },
    { id: 4205, postId: 42, author: '나도신입', content: '저도 고민 중인데 연락 드려도 될까요?', time: '36분 전' },
    { id: 4206, postId: 42, author: '형님짱', content: '솔직한 후기 감사해요 진짜 도움돼요', time: '44분 전' },
    { id: 4207, postId: 42, author: '궁금증해소', content: '숙소 지원은 있나요?', time: '52분 전' },
    { id: 4208, postId: 42, author: '파이팅', content: '앞으로도 잘 되실 거예요!', time: '58분 전' },
    // postId: 82 (1억 인증)
    { id: 8201, postId: 82, author: '대단해요', content: '진짜 대단하세요! 팁 좀 공유해주세요!!', time: '8분 전' },
    { id: 8202, postId: 82, author: '나도할수있을까', content: '투잡은 어떤 걸 하셨어요?', time: '18분 전' },
    { id: 8203, postId: 82, author: '응원해', content: '대단해요 정말!! 앞으로도 잘 되세요!', time: '30분 전' },
    { id: 8204, postId: 82, author: '재테크형님', content: '적금 말고 투자 포트폴리오 어떻게 짜셨어요?', time: '42분 전' },
    // postId: 88 (업소 고르는 기준)
    { id: 8801, postId: 88, author: '궁금해요', content: '매니저 스타일은 어떻게 파악하세요?', time: '10분 전' },
    { id: 8802, postId: 88, author: '유용해요', content: '체크리스트 정리해서 메모해뒀어요', time: '22분 전' },
    { id: 8803, postId: 88, author: '더알고싶어', content: '수수료율 적정선이 어느 정도예요?', time: '35분 전' },
    // postId: 17 (멘탈 관리)
    { id: 1701, postId: 17, author: '공감해요', content: '야간 근무 후 산책이 진짜 효과 있어요', time: '20분 전' },
    { id: 1702, postId: 17, author: '헬스추천', content: '헬스 시작하면서 확실히 달라졌어요', time: '40분 전' },
    { id: 1703, postId: 17, author: '루틴만들기', content: '형님 루틴 더 구체적으로 공유해주실 수 있어요?', time: '55분 전' },
    // postId: 1 (퇴근길 하늘)
    { id: 1001, postId: 1, author: '공감', content: '새벽 퇴근길 하늘이 진짜 힐링이죠 ㅠ', time: '8분 전' },
    { id: 1002, postId: 1, author: '파이팅', content: '내일도 파이팅 형님!', time: '3분 전' },
    // postId: 100 (세후 500)
    { id: 10001, postId: 100, author: '축하해요', content: '축하드려요! 어떤 점 바꾸셨어요?', time: '5분 전' },
    { id: 10002, postId: 100, author: '나도목표', content: '저도 목표로 잡겠습니다!', time: '15분 전' },
    { id: 10003, postId: 100, author: '응원해요', content: '대단하세요 진짜로!', time: '25분 전' },
    // postId: 101 (고민중)
    { id: 10101, postId: 101, author: '경험자', content: '처음엔 다 걱정하죠. 해보면 생각보다 괜찮아요', time: '10분 전' },
    { id: 10102, postId: 101, author: '현실조언', content: '업소 선택이 제일 중요해요. 꼼꼼히 알아보세요', time: '20분 전' },
    { id: 10103, postId: 101, author: '신중하게', content: '서두르지 말고 여러 군데 비교해보세요', time: '35분 전' },
    // postId: 50 (VIP 테이블)
    { id: 5001, postId: 50, author: '영어공부해야겠다', content: '저도 이런 상황 대비해서 영어 공부 시작했어요 ㅋㅋ', time: '10분 전' },
    { id: 5002, postId: 50, author: '팁받으셨다니', content: '위기를 기회로 바꾸셨네요 대단해요!', time: '18분 전' },
    { id: 5003, postId: 50, author: '레전드', content: 'ㅋㅋㅋ 상상만해도 웃기다', time: '25분 전' },
    // postId: 51 (카드 거꾸로)
    { id: 5101, postId: 51, author: '표정관리ㅋㅋ', content: '표정 관리가 진짜 프로네요 ㅋㅋ', time: '8분 전' },
    { id: 5102, postId: 51, author: '공감', content: '이런 순간 참기 힘들죠 ㅋㅋ', time: '17분 전' },
    // postId: 41 (단골 관리)
    { id: 4101, postId: 41, author: '메모장쓰기시작', content: '저도 오늘부터 손님 메모 시작했어요!', time: '5분 전' },
    { id: 4102, postId: 41, author: '30프로증가', content: '30% 올랐다니 대단해요. 구체적인 방법 더 알려주세요', time: '14분 전' },
    { id: 4103, postId: 41, author: '당장적용', content: '기념일 챙기는 거 진짜 효과 좋더라고요', time: '22분 전' },
    // postId: 90 (면접 확인사항)
    { id: 9001, postId: 90, author: '유용해요', content: '이 4가지 다음 면접에서 꼭 확인할게요', time: '5분 전' },
    { id: 9002, postId: 90, author: '구두약속절대안돼', content: '저 구두 약속 믿었다가 손해봤어요 ㅠ', time: '14분 전' },
    { id: 9003, postId: 90, author: '감사합니다', content: '계약서 조항까지 정리해주셔서 너무 유용해요', time: '22분 전' },
    // postId: 83 (강남 분위기)
    { id: 8301, postId: 83, author: '강남현직', content: '강남은 요즘도 괜찮아요. 주말 손님이 특히 많네요', time: '12분 전' },
    { id: 8302, postId: 83, author: '이직성공', content: '저 작년에 강남으로 이직했는데 잘한 것 같아요', time: '25분 전' },
    { id: 8303, postId: 83, author: '조심할점', content: '업소마다 편차가 커요. 여러 군데 비교하세요', time: '38분 전' },
    // postId: 84 (홍대 신규)
    { id: 8401, postId: 84, author: '홍대형님1', content: '저도 들은 게 있는데 DM 드릴게요', time: '6분 전' },
    { id: 8402, postId: 84, author: '확인중', content: '저도 알아보고 있는데 정보 나오면 공유할게요', time: '15분 전' },
    // postId: 85 (부산 서면)
    { id: 8501, postId: 85, author: '부산형님1', content: '서면 정보 공유 감사해요! 3번 업소 어디예요?', time: '8분 전' },
    { id: 8502, postId: 85, author: '부산형님2', content: '수수료율 비교가 제일 궁금했는데 잘 정리해주셨네요', time: '18분 전' },
    { id: 8503, postId: 85, author: '이직고민부산', content: '서면 이직 고민 중인데 DM 드려도 될까요?', time: '28분 전' },
    // postId: 93 (체형 관리)
    { id: 9301, postId: 93, author: '헬스시작', content: '저도 작년부터 헬스 시작했는데 확실히 달라지더라고요', time: '6분 전' },
    { id: 9302, postId: 93, author: '단백질중요', content: '단백질 챙기는 거 진짜 중요해요. 닭가슴살 추천!', time: '15분 전' },
    { id: 9303, postId: 93, author: '루틴공유', content: '낮에 헬스가 야간 근무 후 피로 회복에 진짜 좋아요', time: '25분 전' },
];

export const MOCK_POSTS = RAW_MOCK_POSTS;
export const MOCK_COMMENTS = RAW_MOCK_COMMENTS;
