export interface Post {
    id: number;
    category: string;
    title: string;
    content: string;
    author: string;
    time: string;
    likes: number;
    comments: number;
    views?: number;
    isHot?: boolean;
}

export const CATEGORIES = [
    { id: 'all', name: '전체' },
    { id: 'talk', name: '웨이터 소통방' },
    { id: 'region', name: '지역방' },
    { id: 'ssul', name: '웨이터 썰' },
    { id: 'tip', name: '웨이터 팁' },
    { id: 'market', name: '중고거래' },
    { id: 'legal', name: '무료법률상담' },
    { id: 'lounge', name: '프리미엄 라운지' },
] as const;

export type CategoryId = typeof CATEGORIES[number]['id'];

const RAW_MOCK_POSTS: Post[] = [
    {
        id: 40,
        category: '프리미엄 라운지',
        title: '형님들 블랙리스트 공유할게요 (필독)',
        content: '요즘 이상한 손님들이 너무 많네요. 제가 직접 겪은 블랙리스트 명단 공유합니다. 다들 조심하세요! 특히 00시에 나타나는 30대 중반 키 큰 남자는 진짜 요주의 인물입니다.',
        author: '정보통',
        time: '5분 전',
        likes: 48,
        comments: 6,
        isHot: true,
    },
    {
        id: 41,
        category: '웨이터 팁',
        title: '이번에 새로 나온 샤넬 립스틱 발색 후기',
        content: '샤넬 신상 발라봤는데 역시 하늘 아래 같은 핑크는 없네요.. 이번 시즌 컬러 진짜 대박이에요. 촉촉하면서도 지속력 좋아서 데일리로 딱입니다.',
        author: '뷰티퀸',
        time: '12분 전',
        likes: 38,
        comments: 4,
        isHot: true,
    },
    {
        id: 42,
        category: '프리미엄 라운지',
        title: '오픈 3일차 수입 공개합니다...',
        content: '걱정 많이 했는데 생각보다 잘 벌리네요. 저처럼 고민하는 형님들 위해 용기 내서 올립니다! 첫날에는 좀 헤맸는데 둘째날부터 요령이 생기니까 수입이 확 늘었어요.',
        author: '뉴비형님',
        time: '20분 전',
        likes: 52,
        comments: 8,
        isHot: true,
    },
    {
        id: 50,
        category: '형님들의 수다(썰)',
        title: '회피형 남친이랑 3년 사귀고 환승 당한 썰.. 제가 바보였나요?',
        content: '진짜 손이 떨려서 글 써요. 3년 동안 싸움만 나면 동굴 들어가고 잠수 타던 남친.. 고쳐 보겠다고 옆에서 온갖 정성 다 쏟았는데 결국 한 달 만에 다른 인재 인스타에 럽스타그램 올라오네요. 회피형은 정말 고쳐 쓰는 거 아닌가 봐요.',
        author: '눈물나네',
        time: '25분 전',
        likes: 57,
        comments: 15,
        isHot: true,
    },
    {
        id: 51,
        category: '형님들의 수다(썰)',
        title: '예비 시댁에서 자꾸 혼수를 폰으로 보내는데 이거 어쩌죠?',
        content: '결혼 한 달 남았는데 예비 시어머니가 자꾸 링크를 보내요. 소파부터 가전까지 본인 취향인 것만.. 심지어 가격대도 만만치 않은데 저희 형편은 생각도 안 하시나 봐요. 남친은 효자라 말도 못 하고.. 파혼 각인가요?',
        author: '답답해',
        time: '40분 전',
        likes: 44,
        comments: 12,
        isHot: true,
    },
    {
        id: 52,
        category: '형님들의 수다(썰)',
        title: '어제 손님으로 온 전남친이랑 마주쳤습니다 (심장 터질뻔)',
        content: '알바하는데 문 열고 들어오는 사람이 너무 낯익어서 봤더니 2년 전에 헤어진 전남친.. 옆에는 예쁜 인재분 데리고 왔더라고요. 저랑 눈 마주쳤는데 모르는 척하더라고요. 화장실 가서 한참 울다 나왔네요.',
        author: '멘탈바사삭',
        time: '1시간 전',
        likes: 59,
        comments: 22,
        isHot: true,
    },
    {
        id: 53,
        category: '형님들의 수다(썰)',
        title: '30대 형님들아, 연애할 때 이거 꼭 보세요 (결혼 조건)',
        content: '나이 먹고 연애하려니까 감정보다는 조건부터 보게 되네요. 근데 제가 깨달은 건 돈보다 인성이 1순위라는 거예요. 아무리 돈 많아도 말 예쁘게 안 하는 남자는 결국 상처만 주더라고요. 형님들은 뭘 보시나요?',
        author: '경험담',
        time: '2시간 전',
        likes: 31,
        comments: 9,
    },
    {
        id: 54,
        category: '형님들의 수다(썰)',
        title: '여우 같은 여우 짓? 제가 한 번 해봤습니다 ㅋㅋ',
        content: '평범한 제가 이번에 맘에 드는 남자 꼬시려고 여우 짓 좀 해봤는데 대성공했어요! 역시 남자는 칭찬과 리액션에 약하네요. 혹시 궁금한 형님들 있으면 댓글 달아주세요 공유할게요!',
        author: '성공적',
        time: '3시간 전',
        likes: 41,
        comments: 18,
        isHot: true,
    },
    {
        id: 1,
        category: '웨이터 썰',
        title: '오늘 퇴근길 노을 보셨나요? 진짜 힐링..✨',
        content: '요즘 일하느라 너무 바빴는데 잠깐 고개 들어보니 하늘이 너무 예쁘더라고요. 형님들도 오늘 하루 고생 많으셨어요!',
        author: '익명123',
        time: '10분 전',
        likes: 12,
        comments: 2,
    },
    {
        id: 17,
        category: '프리미엄 라운지',
        title: '멘탈 관리하는 나만의 루틴 공유 🧘',
        content: '명상이랑 가벼운 독서가 큰 도움이 되네요. 바쁜 일상 속에서도 마음의 여유를 찾는 팁들입니다.',
        author: '퀸즈',
        time: '1시간 전',
        likes: 29,
        comments: 5,
    },
    {
        id: 6,
        category: '웨이터 썰',
        title: '동네 맛집 추천 좀 해주세요 (강남역 근처)',
        content: '오늘 친구랑 만나기로 했는데 조용하고 분위기 좋은 곳 있을까요? 파스타나 일식 선호합니다!',
        author: '배고픈다람쥐',
        time: '4시간 전',
        likes: 9,
        comments: 3,
    },
    {
        id: 18,
        category: '웨이터 썰',
        title: '멀티비타민 이거 진짜 물건이네요 ㅋㅋ',
        content: '직업 특성상 피로를 달고 사는데.. 이거 먹고 나서부터 아침이 달라요. 내돈내산 찐후기입니다.',
        author: '비타민짱',
        time: '45분 전',
        likes: 15,
        comments: 4,
    },
    {
        id: 33,
        category: '프리미엄 라운지',
        title: '남사친이 자꾸 선 넘는데, 이거 썸인가요? 🙄',
        content: '맨날 먼저 연락 오고, 술 마시자고 하는데 막상 만나면 그냥 친구 같아요. 형님들이 보기엔 어떤가요?',
        author: '고민녀',
        time: '30분 전',
        likes: 15,
        comments: 5,
    },
    {
        id: 80,
        category: '형님들의 수다(썰)',
        title: '전남친 결혼식 가서 축의금 1,000원 내고 뷔페 3그릇 먹고 온 썰 ㅋㅋ',
        content: '어차피 모르는 척할 거 뻔해서 아주 화려하게 꾸미고 갔어요. 신부보다 제가 더 예쁘다는 소리 들으니까 기분 최고더라고요. 식권 받아서 랍스터까지 야무지게 챙겨 먹고 왔습니다. 형님들, 최고의 복수는 내가 더 잘 사는 모습을 보여주는 거예요!',
        author: '복수여왕',
        time: '1시간 전',
        likes: 58,
        comments: 21,
        isHot: true,
    },
    {
        id: 81,
        category: '형님들의 수다(썰)',
        title: '첫 출근했는데 사장님이 제 인스타 보더니 홍보 모델 하라네요 ㅠ',
        content: '사무직인 줄 알고 갔는데 제 인스타 팔로워 보더니 갑자기 업체 홍보 영상 찍어보라고.. 페이는 더 준다는데 이거 계속해야 할까요? 제가 하는 일이 바뀔까 봐 걱정돼요.',
        author: '사회초년생',
        time: '2시간 전',
        likes: 36,
        comments: 14,
        isHot: true,
    },
    {
        id: 82,
        category: '프리미엄 라운지',
        title: '형님들, 20대에 1억 모으기.. 진짜 가능한 거였어? (인증)',
        content: '잠 안 자고 투잡 뛰고 재테크 공부해서 드디어 앞자리 바꿨어요! 처음엔 막막했는데 절약하는 법이랑 투자 포트폴리오 짜니까 눈에 보이더라고요. 비결 궁금한 형님들 댓글 주면 제 루틴 공유할게요!',
        author: '자산가형님',
        time: '3시간 전',
        likes: 55,
        comments: 19,
        isHot: true,
    },
    {
        id: 83,
        category: '형님들의 수다(썰)',
        title: '남사친이 자꾸 새벽에 전화해서 전여친 욕하는데.. 손절각이죠?',
        content: '자기는 피해자인 척하면서 전여친만 나쁜X 만드는데, 듣고 있으면 제가 다 기가 빨려요. 처음엔 위로해 줬는데 매일 이러니까 이제는 전화벨만 울려도 짜증 나네요. 그냥 조용히 차단할까요?',
        author: '기빨려요',
        time: '4시간 전',
        likes: 27,
        comments: 11,
    },
    {
        id: 84,
        category: '형님들의 수다(썰)',
        title: '어제 클럽에서 만난 남자가 알고 보니 울 회사 거래처 팀장님 ㅋㅋㅋ',
        content: '어쩐지 어디서 많이 본 얼굴이다 싶었는데.. 오늘 미팅에서 마주치고 서로 눈 피하느라 죽는 줄 알았네요 ㅋㅋ 그분도 당황한 게 눈에 보이는데 앞으로 어떡하죠?',
        author: '민망한만남',
        time: '5시간 전',
        likes: 53,
        comments: 24,
        isHot: true,
    },
    {
        id: 85,
        category: '형님들의 수다(썰)',
        title: '소개팅에서 밥 먹고 2차로 편의점 가서 캔맥주 마시자는 남자.. 어때요?',
        content: '분위기 좋은 술집 가자니까 자기 아는 단골 노상 맛집이 있다면서 편의점 앞 테이블로 데려가네요.. 날씨도 추운데 이게 맞는 건지.. 제가 너무 까다로운 건가요?',
        author: '황당그잡채',
        time: '6시간 전',
        likes: 46,
        comments: 28,
        isHot: true,
    },
    {
        id: 86,
        category: '형님들의 수다(썰)',
        title: '남친의 은밀한 취미.. 이거 이해해줘야 하나요? (고민)',
        content: '남친이 피규어 수집하는 건 알았는데, 그 가격이 제가 생각한 것보다 훨씬 높더라고요. 이번 달 월급의 절반을 썼다는데 앞으로 결혼 자금은 언제 모으려고 이러는지 모르겠어요. 취존 해줘야 할까요?',
        author: '취미전쟁',
        time: '8시간 전',
        likes: 22,
        comments: 17,
    },
    {
        id: 87,
        category: '형님들의 수다(썰)',
        title: '30대 솔로 형님들, 이번 명절 대피소 어디로 가세요? ✈️',
        content: '잔소리 듣기 싫어서 저는 혼자 호캉스 예약했어요! 차라리 돈 좀 쓰고 마음 편한 게 최고네요. 형님들은 명절에 어떻게 시간을 보내시는지 궁금해요!',
        author: '행복한싱글',
        time: '12시간 전',
        likes: 49,
        comments: 20,
        isHot: true,
    },
    {
        id: 88,
        category: '프리미엄 라운지',
        title: '성공한 형님가 말해주는 "부자 남친" 만나는 법 🤫',
        content: '단순히 예쁜 것보다 중요한 건 본인의 가치를 높이는 거예요. 그들이 모이는 장소, 나누는 대화 주제를 공부하세요. 제가 직접 겪은 상위 1% 남자들의 특징과 공략법 공유합니다.',
        author: '성공학개론',
        time: '15시간 전',
        likes: 60,
        comments: 18,
        isHot: true,
    },
    {
        id: 89,
        category: '형님들의 수다(썰)',
        title: '알바 면접 갔는데 사장님이 제 인스타 팔로워 수부터 물어보네요 ㅋ',
        content: '일 잘하는 건 안 보고 파급력이 얼마나 되는지만 궁금해하는 것 같아서 기분 나빠서 그냥 나왔어요. 요즘은 알바도 셀럽 아니면 못 하나 봐요? 황당해서 글 써봅니다.',
        author: '알바지망생',
        time: '20시간 전',
        likes: 33,
        comments: 13,
    },
    {
        id: 35,
        category: '프리미엄 라운지',
        title: '회피형 인간하고 연애하는 형님들 필독 (탈출기) ✂️',
        content: '싸우기만 하면 잠수 타는 전남친 때문에 1년을 고생했네요. 결국 헤어지고 나니까 속이 다 시원해요. 회피형은 고쳐 쓰는 거 아니라는 말, 뼈저리게 느낍니다.',
        author: '탈출성공',
        time: '2시간 전',
        likes: 24,
        comments: 7,
        isHot: true,
    },
    // ── 신규: 연애 공감 게시글 ──────────────────────────────
    {
        id: 90,
        category: '형님들의 수다(썰)',
        title: '남친이 생일 선물로 운동화 사줬는데.. 이게 맞아요? 🤦‍♀️',
        content: '사귄 지 1년이 넘었는데 생일에 케이크도 없고 꽃도 없이 3만원짜리 운동화만 덜렁 왔어요. 쓸모 있는 건 알겠는데 낭만이 1도 없는 남자인 건 알았지만 이건 좀 심한 것 같아서요. 형님들은 어떻게 생각하세요?',
        author: '서운해죽겠음',
        time: '30분 전',
        likes: 43,
        comments: 16,
        isHot: true,
    },
    {
        id: 91,
        category: '형님들의 수다(썰)',
        title: '이별 통보 받은 날 혼자 스테이크 먹은 썰 (셀프위로) 🥩',
        content: '헤어지자는 말 듣고 집에 오자마자 근처 스테이크 집 예약했어요. 혼자서 와인이랑 안심 스테이크 먹으면서 속으로 "내가 더 아깝다" 되뇌었습니다. 근데 진짜 맛있어서 슬픔이 반으로 줄었어요 ㅋㅋ 슬플 때일수록 좋은 거 먹어야 해요!',
        author: '씩씩한형님',
        time: '1시간 전',
        likes: 37,
        comments: 12,
        isHot: true,
    },
    {
        id: 92,
        category: '형님들의 수다(썰)',
        title: '5년 사귄 남친한테 "우리 사이가 뭔지 모르겠어" 들은 썰',
        content: '5년 동안 결혼 얘기까지 했는데 갑자기 이런 말이 나와서 진짜 멘붕이었어요. 알고 보니 직장 여동료랑 친해졌더라고요. 헤어지고 6개월 후에 다시 연락 왔는데 차단이 답이었습니다.',
        author: '5년허비',
        time: '3시간 전',
        likes: 51,
        comments: 26,
        isHot: true,
    },
    {
        id: 93,
        category: '형님들의 수다(썰)',
        title: '남자가 진심으로 좋아할 때 보이는 신호 (착각 금지)',
        content: '소개팅만 100번 나가본 경험으로 정리해봤어요. 1. 먼저 연락이 오는 빈도 2. 약속 잡을 때 구체적으로 잡는지 3. 내 얘기를 더 궁금해하는지. 이 3개 없으면 그냥 킬링타임이에요. 착각하지 마세요!',
        author: '소개팅전문가',
        time: '2시간 전',
        likes: 56,
        comments: 31,
        isHot: true,
    },
    {
        id: 94,
        category: '형님들의 수다(썰)',
        title: '첫눈에 반했는데 남자친구 있는 남자였을 때 현타 ㅠ',
        content: '카페에서 눈 마주쳐서 설렜는데 계산하면서 손가락 봤더니 커플링.. SNS 찾아봤더니 여친이랑 부산 여행 사진이 떠 있네요. 세상 잔인해. 잘생긴 남자는 다 여친 있는 거 아닌가요 ㅠ',
        author: '큰일날뻔',
        time: '4시간 전',
        likes: 29,
        comments: 14,
    },
    {
        id: 95,
        category: '형님들의 수다(썰)',
        title: '카톡 읽씹 3일 만에 온 답장 내용이 충격 ㅋㅋ',
        content: '"미안 핸드폰 고장났었어"인데 카카오톡으로 답장이 왔어요. 핸드폰 고장나면 카톡이 먼저 되냐고요 ㅋㅋ 변명도 좀 그럴싸하게 해라 진짜. 이 남자 어떻게 해야 해요?',
        author: '어이없는상황',
        time: '1시간 전',
        likes: 44,
        comments: 19,
        isHot: true,
    },
];

const RAW_MOCK_COMMENTS = [
    // postId: 1 (노을)
    { id: 1001, postId: 1, author: '봄햇살', content: '맞아요 오늘 노을 진짜 예뻤어요 ㅠㅠ', time: '8분 전' },
    { id: 1002, postId: 1, author: '형님후기', content: '고생 많으셨어요! 내일도 파이팅 ㅎㅎ', time: '3분 전' },
    // postId: 40 (블랙리스트)
    { id: 4001, postId: 40, author: '정보감사', content: '이런 정보 너무 필요했어요! 저장해뒀어요', time: '3분 전' },
    { id: 4002, postId: 40, author: '조심해야지', content: '저도 비슷한 사람 만난 적 있는데 소름이네요', time: '7분 전' },
    { id: 4003, postId: 40, author: '공유고마워', content: '댓글로 추가 제보 주실 분 있나요?', time: '12분 전' },
    { id: 4004, postId: 40, author: '나도신고해', content: '저도 비슷한 케이스 있는데 공유해도 될까요?', time: '20분 전' },
    { id: 4005, postId: 40, author: '진짜무서워', content: '캡처해서 주변 형님들한테 공유했어요', time: '28분 전' },
    { id: 4006, postId: 40, author: '고마워요', content: '이런 글 올려주셔서 진짜 감사해요', time: '35분 전' },
    // postId: 41 (샤넬 립스틱)
    { id: 4101, postId: 41, author: '뷰티러버', content: '저 이거 지난달에 샀는데 발색 진짜 맛집이에요!', time: '5분 전' },
    { id: 4102, postId: 41, author: '궁금해요', content: '어느 색상 쓰셨어요? 저도 사고싶어요 ㅠ', time: '14분 전' },
    { id: 4103, postId: 41, author: '립스틱매니아', content: '요즘 샤넬 립 퀄이 많이 올라간 것 같아요', time: '22분 전' },
    { id: 4104, postId: 41, author: '혜택드림', content: '면세점에서 사면 좀 더 저렴해요!', time: '38분 전' },
    // postId: 42 (오픈 3일차)
    { id: 4201, postId: 42, author: '궁금한형님', content: '대박이네요! 어떻게 준비하셨어요?', time: '5분 전' },
    { id: 4202, postId: 42, author: '나도해볼까', content: '저도 고민 중인데 무섭긴 해요 솔직히', time: '12분 전' },
    { id: 4203, postId: 42, author: '응원해요', content: '멋지다!! 저도 용기 내볼게요', time: '20분 전' },
    { id: 4204, postId: 42, author: '리얼후기감사', content: '첫날 어떻게 하셨는지 더 알려주세요!', time: '28분 전' },
    { id: 4205, postId: 42, author: '나도신입', content: '저도 고민 중인데 연락 드려도 될까요?', time: '36분 전' },
    { id: 4206, postId: 42, author: '형님짱', content: '솔직한 후기 감사해요 진짜 도움돼요', time: '44분 전' },
    { id: 4207, postId: 42, author: '궁금증해소', content: '숙식은 어떻게 하세요?', time: '52분 전' },
    { id: 4208, postId: 42, author: '파이팅', content: '앞으로도 잘 되실 거예요!', time: '58분 전' },
    // postId: 50 (회피형 환승)
    { id: 5001, postId: 50, author: '사이다형님', content: '회피형은 절대 안 변해요. 잘 탈출하셨어요!', time: '10분 전' },
    { id: 5002, postId: 50, author: '경험자형님', content: '저도 똑같은 일 겪었는데 지금 너무 행복해요', time: '18분 전' },
    { id: 5003, postId: 50, author: '분노댓글', content: '진짜 뻔뻔하다 어떻게 그럴 수가 있죠', time: '25분 전' },
    { id: 5004, postId: 50, author: '공감100', content: '3년 투자한 게 아까워서라도 화나겠다 ㅠㅠ', time: '33분 전' },
    { id: 5005, postId: 50, author: '힘내요', content: '당신이 더 나은 사람 만날 자격 있어요!', time: '41분 전' },
    { id: 5006, postId: 50, author: '회피형피해자', content: '저도 회피형이랑 2년.. 소름돋는 공감글이에요', time: '50분 전' },
    // postId: 51 (시댁 혼수)
    { id: 5101, postId: 51, author: '냉철하게', content: '그거 시작이에요. 파혼이 답입니다 진짜로.', time: '8분 전' },
    { id: 5102, postId: 51, author: '경험담', content: '결혼 후에도 이런 분들 더 심해져요', time: '17분 전' },
    { id: 5103, postId: 51, author: '현실조언', content: '남친이 중간에서 조율 못 하면 결혼 후에도 이럴 거예요', time: '26분 전' },
    { id: 5104, postId: 51, author: '같은처지', content: '저도 비슷한 상황인데 공감 100%예요 ㅠ', time: '35분 전' },
    { id: 5105, postId: 51, author: '응원해요', content: '어떤 결정을 하든 응원해요!', time: '44분 전' },
    // postId: 52 (전남친 마주침)
    { id: 5201, postId: 52, author: '눈물쓱', content: '아이고.. 맘고생 심하셨겠어요. 맛있는 거 먹고 털어버려요!', time: '5분 전' },
    { id: 5202, postId: 52, author: '공감최고', content: '모르는 척 하는 거 진짜 더 상처받죠 ㅠ', time: '14분 전' },
    { id: 5203, postId: 52, author: '화나는중', content: '옆에 인재분이랑 어떻게 보였어요?', time: '23분 전' },
    { id: 5204, postId: 52, author: '응원합니다', content: '울지 마세요~ 당신이 훨씬 나은 사람이에요!', time: '32분 전' },
    { id: 5205, postId: 52, author: '나도그랬어', content: '저도 비슷한 경험 있는데 진짜 지옥이었어요 ㅠ', time: '41분 전' },
    // postId: 53 (결혼 조건)
    { id: 5301, postId: 53, author: '공감해요', content: '인성이 1순위라는 거 진짜 맞아요', time: '15분 전' },
    { id: 5302, postId: 53, author: '30대공감', content: '저도 조건보다 같이 있을 때 편한 사람으로 바뀌었어요', time: '30분 전' },
    { id: 5303, postId: 53, author: '현실형님', content: '형님 말 맞아요. 경험이 최고의 스승이에요', time: '45분 전' },
    // postId: 54 (여우 짓)
    { id: 5401, postId: 54, author: '나도알려줘', content: '저도 알고 싶어요!! 댓글로 공유 부탁드려요ㅠ', time: '8분 전' },
    { id: 5402, postId: 54, author: '성공비법궁금', content: '어떤 칭찬이 제일 효과적이었어요?', time: '18분 전' },
    { id: 5403, postId: 54, author: '리액션이답', content: '리액션이 핵심이라는 거 진짜 공감 ㅋㅋ', time: '28분 전' },
    // postId: 17 (멘탈 관리)
    { id: 1701, postId: 17, author: '명상초보', content: '명상 어떻게 시작하셨어요? 저도 해보고 싶어요', time: '20분 전' },
    { id: 1702, postId: 17, author: '독서형님', content: '독서 진짜 도움 많이 돼요 공감이에요', time: '40분 전' },
    { id: 1703, postId: 17, author: '루틴만들기', content: '저도 루틴 만들어보고 싶은데 추천 책 있나요?', time: '55분 전' },
    // postId: 6 (맛집 추천)
    { id: 601, postId: 6, author: '강남토박이', content: '가로수길 쪽 이탈리안 레스토랑 분위기 좋아요!', time: '30분 전' },
    { id: 602, postId: 6, author: '미식가형님', content: '신사역 근처 일식 오마카세 강추예요~', time: '1시간 전' },
    { id: 603, postId: 6, author: '카페추천', content: '투썸플레이스 말고 조용한 카페들도 많아요 ㅎ', time: '2시간 전' },
    // postId: 18 (멀티비타민)
    { id: 1801, postId: 18, author: '비타민관심', content: '어떤 브랜드 쓰세요? 저도 사보고 싶어요!', time: '15분 전' },
    { id: 1802, postId: 18, author: '피로만성', content: '저도 피로가 항상 심한데 진짜 효과 있나요?', time: '30분 전' },
    { id: 1803, postId: 18, author: '건강형님', content: '내돈내산 후기 믿을 수 있어서 좋아요 ㅎㅎ', time: '50분 전' },
    // postId: 33 (남사친 썸)
    { id: 3301, postId: 33, author: '썸전문가', content: '막상 만나면 그냥 친구같다는 게 답 아닐까요..', time: '10분 전' },
    { id: 3302, postId: 33, author: '직진해봐', content: '솔직하게 물어보는 게 제일 빠를 것 같아요!', time: '22분 전' },
    { id: 3303, postId: 33, author: '경험자', content: '저도 그런 남사친 있었는데 그냥 친구였어요ㅠ', time: '38분 전' },
    // postId: 80 (전남친 결혼식)
    { id: 8001, postId: 80, author: '레전드', content: 'ㅋㅋㅋㅋ 1000원이요? 사이다 그 자체!!', time: '5분 전' },
    { id: 8002, postId: 80, author: '랍스터까지', content: '랍스터까지 챙기셨다니 진짜 소름 ㅋㅋ 최고예요', time: '12분 전' },
    { id: 8003, postId: 80, author: '최고의복수', content: '이게 진짜 클래스 복수지 ㅋㅋ 멋있어요!', time: '20분 전' },
    { id: 8004, postId: 80, author: '박수쳐', content: '최고의 복수란 내가 더 잘 사는 모습이죠 인정!', time: '30분 전' },
    { id: 8005, postId: 80, author: '신부보다예뻤겠다', content: '상상만으로도 통쾌하다 ㅋㅋ', time: '42분 전' },
    // postId: 81 (인스타 홍보 모델)
    { id: 8101, postId: 81, author: '경험자', content: '그 상황 애매하긴 하죠.. 계약서부터 받아보세요', time: '10분 전' },
    { id: 8102, postId: 81, author: '노동상담', content: '직무 변경은 근로계약 위반이에요. 확인해봐요', time: '20분 전' },
    { id: 8103, postId: 81, author: '인스타팔로워', content: '팔로워 몇 명이에요? ㅋㅋ 저도 비슷한 제안 받았어요', time: '30분 전' },
    { id: 8104, postId: 81, author: '신중하게', content: '페이가 얼마나 올랐는지에 따라 판단하세요', time: '42분 전' },
    // postId: 82 (1억 인증)
    { id: 8201, postId: 82, author: '대단해요', content: '진짜 대단하세요! 팁 좀 공유해주세요!!', time: '8분 전' },
    { id: 8202, postId: 82, author: '나도할수있을까', content: '투잡은 어떤 걸 하셨어요?', time: '18분 전' },
    { id: 8203, postId: 82, author: '응원해', content: '대단해요 정말!! 앞으로도 잘 되세요!', time: '30분 전' },
    { id: 8204, postId: 82, author: '재테크형님', content: '포트폴리오 어떻게 짜셨어요? 궁금해요', time: '42분 전' },
    // postId: 83 (남사친 전여친 욕)
    { id: 8301, postId: 83, author: '손절각', content: '기빨리는 사람은 끊어내야 해요. 손절각 맞아요', time: '12분 전' },
    { id: 8302, postId: 83, author: '공감', content: '전여친 욕하는 남자는 당신 욕도 하고 다녀요 조심해요', time: '25분 전' },
    { id: 8303, postId: 83, author: '경험담', content: '저도 비슷한 남사친 있었는데 조용히 거리 뒀어요', time: '38분 전' },
    // postId: 84 (거래처 팀장)
    { id: 8401, postId: 84, author: 'ㅋㅋ공감', content: 'ㅋㅋㅋㅋ 상상만해도 어색해 죽겠다 ㅠㅠ', time: '6분 전' },
    { id: 8402, postId: 84, author: '프로페셔널', content: '모른 척하고 쿨하게 지내는 게 최선이에요 ㅋㅋ', time: '15분 전' },
    { id: 8403, postId: 84, author: '상상불가', content: '미팅에서 눈 피하는 상황 생각하니 너무 웃김 ㅋㅋ', time: '25분 전' },
    { id: 8404, postId: 84, author: '오히려좋아', content: '그 팀장님도 조용히 하실 거예요 걱정 마요 ㅋㅋ', time: '35분 전' },
    // postId: 85 (편의점 2차)
    { id: 8501, postId: 85, author: '이건아니지', content: '추운 날 편의점 앞 야외 테이블은 좀 아니죠ㅠ', time: '8분 전' },
    { id: 8502, postId: 85, author: '취향차이', content: '돈 아끼는 건지 낭만 없는 건지 ㅋㅋ', time: '18분 전' },
    { id: 8503, postId: 85, author: '2차중요해', content: '첫 소개팅 2차가 편의점이면 저도 좀 실망할 것 같아요', time: '28분 전' },
    { id: 8504, postId: 85, author: '까다롭지않아', content: '까다로운 게 아니에요. 상대방 센스가 없는 거예요', time: '38분 전' },
    // postId: 86 (피규어 취미)
    { id: 8601, postId: 86, author: '취존vs현실', content: '취미는 존중하지만 결혼 자금 의논은 해봐야죠', time: '12분 전' },
    { id: 8602, postId: 86, author: '피규어러버', content: '피규어 수집 비용 꽤 나가죠 ㅠ 저희 남자친구도 그래서 대화 많이 했어요', time: '25분 전' },
    { id: 8603, postId: 86, author: '현실조언', content: '결혼 전에 재정 계획 같이 세워보세요. 지금이 타이밍이에요', time: '40분 전' },
    // postId: 87 (명절 대피소)
    { id: 8701, postId: 87, author: '나도호캉스', content: '저도 올해부터 명절 호캉스로 바꿨어요 진짜 꿀이에요!', time: '15분 전' },
    { id: 8702, postId: 87, author: '해외파', content: '저는 명절에 아예 해외로 나가요 ㅋㅋ 잔소리 제로', time: '30분 전' },
    { id: 8703, postId: 87, author: '공감솔로', content: '잔소리 듣는 게 제일 스트레스에요 ㅠ 공감해요', time: '45분 전' },
    { id: 8704, postId: 87, author: '호캉스추천', content: '어느 호텔로 가셨어요? 저도 알아보고 싶어요', time: '1시간 전' },
    // postId: 88 (부자 남친)
    { id: 8801, postId: 88, author: '궁금해요', content: '어떤 장소에 가야 그런 분들을 만날 수 있나요?', time: '10분 전' },
    { id: 8802, postId: 88, author: '현실적인조언', content: '자기 가치를 높이는 게 먼저라는 말 진짜 공감해요', time: '22분 전' },
    { id: 8803, postId: 88, author: '더알고싶어', content: '구체적인 팁 더 공유해주시면 감사할 것 같아요!', time: '35분 전' },
    // postId: 89 (알바 팔로워)
    { id: 8901, postId: 89, author: '황당공감', content: '진짜 요즘 이런 데 많아요 저도 비슷한 거 겪었어요 ㅋㅋ', time: '15분 전' },
    { id: 8902, postId: 89, author: '인플루언서시대', content: '이제 알바도 인플루언서 시대가 된 건가 ㅋㅋ', time: '30분 전' },
    { id: 8903, postId: 89, author: '잘나오셨어요', content: '그냥 나오신 게 맞는 것 같아요. 그런 사장님 별로예요', time: '45분 전' },
    // postId: 35 (회피형 탈출기)
    { id: 3501, postId: 35, author: '회피형탈출', content: '저도 드디어 탈출했는데 진짜 후련해요 공감해요!', time: '20분 전' },
    { id: 3502, postId: 35, author: '아직진행중', content: '저는 아직 진행 중인데 용기 내야 할 것 같아요 ㅠ', time: '40분 전' },
    { id: 3503, postId: 35, author: '회피형절대no', content: '회피형은 진짜 고쳐 쓰는 거 아니에요. 공감 1000%', time: '1시간 전' },
    // postId: 90 (생일 운동화)
    { id: 9001, postId: 90, author: '서운함공감', content: '저라도 서운할 것 같아요.. 케이크 하나 없이요?', time: '5분 전' },
    { id: 9002, postId: 90, author: '낭만없는남자', content: '1년 넘었으면 이제 취향 알 때도 됐는데 ㅠ', time: '14분 전' },
    { id: 9003, postId: 90, author: '솔직한얘기', content: '말 안 하면 모르는 남자들도 있어요. 한번 얘기해봤어요?', time: '22분 전' },
    { id: 9004, postId: 90, author: '공감100', content: '선물이 문제가 아니라 마음이 없는 거 같아서 더 서운하죠', time: '30분 전' },
    { id: 9005, postId: 90, author: '경험담형님', content: '저도 비슷한 남자 만났는데 결국 헤어졌어요', time: '42분 전' },
    // postId: 91 (이별 스테이크)
    { id: 9101, postId: 91, author: '박수', content: '진짜 최고의 셀프위로다!! 멋있어요 ㅋㅋ', time: '5분 전' },
    { id: 9102, postId: 91, author: '어디식당이에요', content: '어느 스테이크집 가셨어요? 저도 가보고싶어요 ㅋㅋ', time: '15분 전' },
    { id: 9103, postId: 91, author: '씩씩하다', content: '"내가 더 아깝다"는 마인드 너무 좋아요 본받을게요!', time: '25분 전' },
    { id: 9104, postId: 91, author: '슬플때맛집', content: '슬플 때 맛있는 거 먹어야 한다는 거 진리임 ㅠ', time: '38분 전' },
    // postId: 92 (5년 남친)
    { id: 9201, postId: 92, author: '충격이야', content: '5년이요?? 진짜 사람이 어떻게 그럴 수 있는지..', time: '8분 전' },
    { id: 9202, postId: 92, author: '잘하셨어요', content: '다시 연락 온 거 차단하신 거 진짜 잘하셨어요!', time: '18분 전' },
    { id: 9203, postId: 92, author: '분노', content: '직장 동료랑 가까워지는 거 진짜 위험신호인데 ㅠ', time: '28분 전' },
    { id: 9204, postId: 92, author: '공감해요', content: '저도 비슷한 경험... 정말 힘드셨겠다', time: '38분 전' },
    { id: 9205, postId: 92, author: '응원', content: '더 좋은 사람 만나실 거예요 꼭!', time: '48분 전' },
    { id: 9206, postId: 92, author: '현실직시', content: '5년인데 그 말이 나온다는 게 이미 답 나온 거예요', time: '58분 전' },
    // postId: 93 (좋아하는 신호)
    { id: 9301, postId: 93, author: '저장함', content: '캡처해뒀어요 ㅋㅋ 소개팅 100번이 갑이네요', time: '6분 전' },
    { id: 9302, postId: 93, author: '공감만렙', content: '3번 진짜 맞아요. 내 얘기 궁금해하는 사람이 진짜예요', time: '15분 전' },
    { id: 9303, postId: 93, author: '도움받음', content: '현재 썸남한테 적용해봤는데 해당사항 없음 ㅠ', time: '25분 전' },
    { id: 9304, postId: 93, author: '현실직시형님', content: '2번이 핵심! 막연하게 보자는 사람은 진짜 아닌 거였음', time: '35분 전' },
    { id: 9305, postId: 93, author: '경험담', content: '소개팅 100번이면 진짜 고수네요 믿을 수 있어요', time: '45분 전' },
    // postId: 94 (커플링)
    { id: 9401, postId: 94, author: '슬프다', content: '잘생긴 남자는 다 여친 있다는 게 진짜인 것 같아요 ㅠ', time: '10분 전' },
    { id: 9402, postId: 94, author: '손가락확인', content: '저도 이제부터 손가락부터 확인할게요 ㅋㅋ', time: '22분 전' },
    { id: 9403, postId: 94, author: '공감', content: '그 설렘이 한순간에 사라지는 느낌.. 진짜 현타오죠', time: '35분 전' },
    { id: 9404, postId: 94, author: '위로', content: '더 좋은 만남이 기다리고 있을 거예요!', time: '50분 전' },
    // postId: 95 (읽씹 핑계)
    { id: 9501, postId: 95, author: '말이되냐', content: '핸드폰 고장났는데 카톡으로 답장 ㅋㅋㅋㅋ 논리천재', time: '5분 전' },
    { id: 9502, postId: 95, author: '차단각', content: '그냥 차단이 답인 것 같아요 ㅋㅋ', time: '15분 전' },
    { id: 9503, postId: 95, author: '황당공감', content: '변명도 좀 그럴싸하게 해야지 ㅋㅋ 어이없네', time: '25분 전' },
    { id: 9504, postId: 95, author: '이런남자', content: '솔직하게 바빴다고 하면 될 걸 왜 저러는지 ㅠ', time: '38분 전' },
];

export const MOCK_POSTS = RAW_MOCK_POSTS;
export const MOCK_COMMENTS = RAW_MOCK_COMMENTS;
